using BookShop.Dal.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BookShop.Dal.EntityConfiguration;

internal class AuthorEntityConfiguration : IEntityTypeConfiguration<Author>
{
    public void Configure(EntityTypeBuilder<Author> builder)
    {
        builder.HasKey(e => e.Id);

        builder.Property(e => e.Name).HasMaxLength(100);
        builder.Property(e => e.PhotoUrl).HasMaxLength(255);
    }

    public static void SeedData(EntityTypeBuilder<Author> builder)
    {
        builder.HasData(
            new Author { Id = 1,   Name = "Lam Kam Chuen Mester" },
            new Author { Id = 2,   Name = "Susanne Schumacher" },
            new Author { Id = 3,   Name = "Ernest J.Eitel" },
            new Author { Id = 4,   Name = "Simon Brown" },
            new Author { Id = 5,   Name = "François Villon" },
            new Author { Id = 6,   Name = "Sándor László, Pocsai Katalin" },
            new Author { Id = 7,   Name = "Raymond Lo" },
            new Author { Id = 8,   Name = "Jes T.Y.Lim" },
            new Author { Id = 9,   Name = "Fekete Zoltán, Zalay Miklós" },
            new Author { Id = 10,  Name = "Gill Hale, Mark Evans" },
            new Author { Id = 11,  Name = "Szilvásy Judit" },
            new Author { Id = 12,  Name = "Stanislav Grof, Christina Grof" },
            new Author { Id = 13,  Name = "Judy Allen" },
            new Author { Id = 14,  Name = "Jhampa Shaneman, Jan V.Angel" },
            new Author { Id = 15,  Name = "Horváth Andrea" },
            new Author { Id = 16,  Name = "Claus Reimann" },
            new Author { Id = 17,  Name = "Tomasz Lem" },
            new Author { Id = 18,  Name = "Tai San" },
            new Author { Id = 19,  Name = "Robert Powell" },
            new Author { Id = 20,  Name = "Bakos Attila" },
            new Author { Id = 21,  Name = "Julia Parker, Derek Parker" },
            new Author { Id = 22,  Name = "Kalo Jenő" },
            new Author { Id = 23,  Name = "Buji Ferenc" },
            new Author { Id = 24,  Name = "Késmárki László" },
            new Author { Id = 25,  Name = "Koffi Kwahulé" },
            new Author { Id = 26,  Name = "Madách Imre" },
            new Author { Id = 27,  Name = "Spiró György" },
            new Author { Id = 28,  Name = "Isa Schneider" },
            new Author { Id = 29,  Name = "Solara" },
            new Author { Id = 30,  Name = "Alfred Jarry" },
            new Author { Id = 31,  Name = "Faludy György" },
            new Author { Id = 32,  Name = "Paulinyi Tamás" },
            new Author { Id = 33,  Name = "Brian Haughton" },
            new Author { Id = 34,  Name = "Ronald H.Hulnick, Mary R.Hulnick" },
            new Author { Id = 35,  Name = "José ifj.Silva, Ed ifj.Bernd" },
            new Author { Id = 36,  Name = "Lou Aronica, Ken, Sir Robinson" },
            new Author { Id = 37,  Name = "Charles T.Tart" },
            new Author { Id = 38,  Name = "Lisa Rogak" },
            new Author { Id = 39,  Name = "Kornis Mihály" },
            new Author { Id = 40,  Name = "Börcsök László" },
            new Author { Id = 41,  Name = "Veszprémi Tamás" },
            new Author { Id = 42,  Name = "Pierre Merle" },
            new Author { Id = 43,  Name = "Komáromi Gabriella" },
            new Author { Id = 44,  Name = "Ingmar Bergman" },
            new Author { Id = 45,  Name = "Oliver Sacks" },
            new Author { Id = 46,  Name = "Ámosz Oz" },
            new Author { Id = 47,  Name = "Alexander Brody" },
            new Author { Id = 48,  Name = "Cecilie Loveid" },
            new Author { Id = 49,  Name = "Jon Fosse" },
            new Author { Id = 50,  Name = "Alighieri Dante" },
            new Author { Id = 51,  Name = "Arthur Miller" },
            new Author { Id = 52,  Name = "dr.Popper Péter" },
            new Author { Id = 53,  Name = "Tom Bryan" },
            new Author { Id = 54,  Name = "Röhrig Géza" },
            new Author { Id = 55,  Name = "William Shakespeare" },
            new Author { Id = 56,  Name = "Dsida Jenő" },
            new Author { Id = 57,  Name = "Arany János" },
            new Author { Id = 58,  Name = "Andrási Tiborné, Czeglédy István, dr.Czeglédy Istvánné" },
            new Author { Id = 59,  Name = "Berkes Klára" },
            new Author { Id = 60,  Name = "Tony Crilly" },
            new Author { Id = 61,  Name = "Stuart Clark" },
            new Author { Id = 62,  Name = "Katona Gyula Y., Recski András, Szabó Csaba" },
            new Author { Id = 63,  Name = "Obádovics J.Gyula" },
            new Author { Id = 64,  Name = "Halász Ágnes" },
            new Author { Id = 65,  Name = "Theodore Gray" },
            new Author { Id = 66,  Name = "Lente Gábor, Kovács Lajos, Gunda Tamás, Csupor Dezső" },
            new Author { Id = 67,  Name = "Kremmer Tibor, Torkos Kornél" },
            new Author { Id = 68,  Name = "Adam Smith" },
            new Author { Id = 69,  Name = "Zugorné Rácz Éva" },
            new Author { Id = 70,  Name = "Stefan Kassay" },
            new Author { Id = 71,  Name = "Kornai János" },
            new Author { Id = 72,  Name = "Galbács Péter" },
            new Author { Id = 73,  Name = "Simon Bishop, Mike Walker" },
            new Author { Id = 74,  Name = "Csáki György" },
            new Author { Id = 75,  Name = "N.Gregory Mankiw" },
            new Author { Id = 76,  Name = "Kopátsy Sándor" },
            new Author { Id = 77,  Name = "Csurgó Sándor" },
            new Author { Id = 78,  Name = "Dóry Béla" },
            new Author { Id = 79,  Name = "Enzo Gallori" },
            new Author { Id = 80,  Name = "Tóth Gábor" },
            new Author { Id = 81,  Name = "Vajta Gábor" },
            new Author { Id = 82,  Name = "I.N.Smeretle" },
            new Author { Id = 83,  Name = "Monika Offenberger" },
            new Author { Id = 84,  Name = "Sarah, dr.Brewer" },
            new Author { Id = 85,  Name = "Róbert Ceman" },
            new Author { Id = 86,  Name = "Ljudmila Ulickaja" },
            new Author { Id = 87,  Name = "Fábián Janka" },
            new Author { Id = 88,  Name = "Jonathan Safran Foer" },
            new Author { Id = 89,  Name = "Elif Shafak" },
            new Author { Id = 90,  Name = "Singer Arje Iván" },
            new Author { Id = 91,  Name = "Büky Anna" },
            new Author { Id = 92,  Name = "Vlagyimir Szorokin" },
            new Author { Id = 93,  Name = "Steven Erikson" },
            new Author { Id = 94,  Name = "J.R.R.Tolkien" },
            new Author { Id = 95,  Name = "Raymond E.Feist, Steve Stirling" },
            new Author { Id = 96,  Name = "George R.R.Martin" },
            new Author { Id = 97,  Name = "Kövesi Péter" },
            new Author { Id = 98,  Name = "R.A.Salvatore" },
            new Author { Id = 99,  Name = "Raymond E.Feist" },
            new Author { Id = 100, Name = "Szappanos Gábor" },
            new Author { Id = 101, Name = "Király - Acampora Anikó" },
            new Author { Id = 102, Name = "Egon Erwin Kisch" },
            new Author { Id = 103, Name = "Szendrődy Szonja" },
            new Author { Id = 104, Name = "Kresley Cole" },
            new Author { Id = 105, Name = "Bertrice Small" },
            new Author { Id = 106, Name = "Julius J.Coach" },
            new Author { Id = 107, Name = "Pedro Almodóvar" },
            new Author { Id = 108, Name = "Cathryn Cooper" },
            new Author { Id = 109, Name = "Carlos Ruiz Zafón" },
            new Author { Id = 110, Name = "Stieg Larsson" },
            new Author { Id = 111, Name = "Szalai Vivien" },
            new Author { Id = 112, Name = "George P.Pelecanos" },
            new Author { Id = 113, Name = "Joanne Fluke" },
            new Author { Id = 114, Name = "Gerritsen Tess" },
            new Author { Id = 115, Name = "Arthur Bernéde" },
            new Author { Id = 116, Name = "Ross Macdonald" },
            new Author { Id = 117, Name = "Bernard Knight" },
            new Author { Id = 118, Name = "Agatha Christie" },
            new Author { Id = 119, Name = "Linda Castillo" },
            new Author { Id = 120, Name = "Martin Delrio" },
            new Author { Id = 121, Name = "Philip K.Dick" },
            new Author { Id = 122, Name = "Alan E.Nourse, William S.Burroughs" },
            new Author { Id = 123, Name = "Robert Charles Wilson" },
            new Author { Id = 124, Name = "Arkagyij Sztrugackij, Borisz Sztrugackij" },
            new Author { Id = 125, Name = "Arthur C.Clarke, Stephen Baxter" },
            new Author { Id = 126, Name = "Szergej Lukjanyenko" },
            new Author { Id = 127, Name = "Frank Herbert" },
            new Author { Id = 128, Name = "Nathan Archer" },
            new Author { Id = 129, Name = "Lisa Jackson" },
            new Author { Id = 130, Name = "Jónás Zsolt" },
            new Author { Id = 131, Name = "Joe Hill" },
            new Author { Id = 132, Name = "Bíró Szabolcs" },
            new Author { Id = 133, Name = "Kathy Reichs" },
            new Author { Id = 134, Name = "Steve Berry" },
            new Author { Id = 135, Name = "Zima Szabolcs" },
            new Author { Id = 136, Name = "Frei Tamás" },
            new Author { Id = 137, Name = "Árpa Attila" },
            new Author { Id = 138, Name = "Sam Barone" },
            new Author { Id = 139, Name = "Andrew Sanders" },
            new Author { Id = 140, Name = "Tracy Chevalier" },
            new Author { Id = 141, Name = "Christian Jacq" },
            new Author { Id = 142, Name = "André Castelot" },
            new Author { Id = 143, Name = "J.M.G.Le Clézio" },
            new Author { Id = 144, Name = "Roberta Rich" },
            new Author { Id = 145, Name = "C.W.Gortner" },
            new Author { Id = 146, Name = "Oliver Bowden" },
            new Author { Id = 147, Name = "Juli Zeh" }
        );
    }
}
