using BookShop.Dal.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BookShop.Dal.EntityConfiguration;

internal class BookAuthorEntityConfiguration : IEntityTypeConfiguration<BookAuthor>
{
    public void Configure(EntityTypeBuilder<BookAuthor> builder)
    {
        /// Defines composite primary key consisting of BookId and AuthorId
        builder.HasKey(e => new { e.BookId, e.AuthorId });

        builder.HasOne(e => e.Book)
            .WithMany(b => b.BookAuthors)
            .HasForeignKey(e => e.BookId)
            .OnDelete(DeleteBehavior.NoAction);

        builder.HasOne(e => e.Author)
            .WithMany(a => a.BookAuthors)
            .HasForeignKey(e => e.AuthorId)
            .OnDelete(DeleteBehavior.NoAction);

    }

    public static void SeedData(EntityTypeBuilder<BookAuthor> builder)
    {
        builder.HasData(
            new BookAuthor { BookId = 1, AuthorId = 1 },
            new BookAuthor { BookId = 2, AuthorId = 2 },
            new BookAuthor { BookId = 3, AuthorId = 3 },
            new BookAuthor { BookId = 4, AuthorId = 4 },
            new BookAuthor { BookId = 5, AuthorId = 5 },
            new BookAuthor { BookId = 6, AuthorId = 6 },
            new BookAuthor { BookId = 7, AuthorId = 7 },
            new BookAuthor { BookId = 8, AuthorId = 8 },
            new BookAuthor { BookId = 9, AuthorId = 9 },
            new BookAuthor { BookId = 10, AuthorId = 8 },
            new BookAuthor { BookId = 11, AuthorId = 10 },
            new BookAuthor { BookId = 12, AuthorId = 11 },
            new BookAuthor { BookId = 13, AuthorId = 12 },
            new BookAuthor { BookId = 14, AuthorId = 13 },
            new BookAuthor { BookId = 15, AuthorId = 14 },
            new BookAuthor { BookId = 16, AuthorId = 15 },
            new BookAuthor { BookId = 17, AuthorId = 16 },
            new BookAuthor { BookId = 18, AuthorId = 17 },
            new BookAuthor { BookId = 19, AuthorId = 18 },
            new BookAuthor { BookId = 20, AuthorId = 19 },
            new BookAuthor { BookId = 22, AuthorId = 20 },
            new BookAuthor { BookId = 23, AuthorId = 21 },
            new BookAuthor { BookId = 24, AuthorId = 22 },
            new BookAuthor { BookId = 25, AuthorId = 23 },
            new BookAuthor { BookId = 26, AuthorId = 24 },
            new BookAuthor { BookId = 27, AuthorId = 25 },
            new BookAuthor { BookId = 28, AuthorId = 26 },
            new BookAuthor { BookId = 29, AuthorId = 27 },
            new BookAuthor { BookId = 30, AuthorId = 28 },
            new BookAuthor { BookId = 31, AuthorId = 29 },
            new BookAuthor { BookId = 32, AuthorId = 30 },
            new BookAuthor { BookId = 33, AuthorId = 31 },
            new BookAuthor { BookId = 34, AuthorId = 32 },
            new BookAuthor { BookId = 35, AuthorId = 33 },
            new BookAuthor { BookId = 36, AuthorId = 34 },
            new BookAuthor { BookId = 37, AuthorId = 35 },
            new BookAuthor { BookId = 38, AuthorId = 36 },
            new BookAuthor { BookId = 39, AuthorId = 37 },
            new BookAuthor { BookId = 40, AuthorId = 42 },
            new BookAuthor { BookId = 41, AuthorId = 39 },
            new BookAuthor { BookId = 42, AuthorId = 40 },
            new BookAuthor { BookId = 43, AuthorId = 41 },
            new BookAuthor { BookId = 44, AuthorId = 42 },
            new BookAuthor { BookId = 45, AuthorId = 43 },
            new BookAuthor { BookId = 46, AuthorId = 44 },
            new BookAuthor { BookId = 47, AuthorId = 45 },
            new BookAuthor { BookId = 48, AuthorId = 46 },
            new BookAuthor { BookId = 49, AuthorId = 47 },
            new BookAuthor { BookId = 51, AuthorId = 48 },
            new BookAuthor { BookId = 52, AuthorId = 49 },
            new BookAuthor { BookId = 53, AuthorId = 50 },
            new BookAuthor { BookId = 54, AuthorId = 51 },
            new BookAuthor { BookId = 55, AuthorId = 52 },
            new BookAuthor { BookId = 56, AuthorId = 53 },
            new BookAuthor { BookId = 58, AuthorId = 54 },
            new BookAuthor { BookId = 60, AuthorId = 55 },
            new BookAuthor { BookId = 61, AuthorId = 56 },
            new BookAuthor { BookId = 62, AuthorId = 57 },
            new BookAuthor { BookId = 64, AuthorId = 58 },
            new BookAuthor { BookId = 66, AuthorId = 59 },
            new BookAuthor { BookId = 67, AuthorId = 60 },
            new BookAuthor { BookId = 68, AuthorId = 61 },
            new BookAuthor { BookId = 69, AuthorId = 62 },
            new BookAuthor { BookId = 70, AuthorId = 63 },
            new BookAuthor { BookId = 71, AuthorId = 64 },
            new BookAuthor { BookId = 72, AuthorId = 65 },
            new BookAuthor { BookId = 73, AuthorId = 66 },
            new BookAuthor { BookId = 74, AuthorId = 67 },
            new BookAuthor { BookId = 75, AuthorId = 68 },
            new BookAuthor { BookId = 76, AuthorId = 69 },
            new BookAuthor { BookId = 77, AuthorId = 70 },
            new BookAuthor { BookId = 78, AuthorId = 71 },
            new BookAuthor { BookId = 79, AuthorId = 72 },
            new BookAuthor { BookId = 80, AuthorId = 73 },
            new BookAuthor { BookId = 81, AuthorId = 74 },
            new BookAuthor { BookId = 82, AuthorId = 75 },
            new BookAuthor { BookId = 83, AuthorId = 76 },
            new BookAuthor { BookId = 84, AuthorId = 77 },
            new BookAuthor { BookId = 85, AuthorId = 78 },
            new BookAuthor { BookId = 88, AuthorId = 79 },
            new BookAuthor { BookId = 89, AuthorId = 80 },
            new BookAuthor { BookId = 90, AuthorId = 81 },
            new BookAuthor { BookId = 91, AuthorId = 98 },
            new BookAuthor { BookId = 92, AuthorId = 82 },
            new BookAuthor { BookId = 93, AuthorId = 83 },
            new BookAuthor { BookId = 94, AuthorId = 84 },
            new BookAuthor { BookId = 95, AuthorId = 85 },
            new BookAuthor { BookId = 95, AuthorId = 86 },
            new BookAuthor { BookId = 97, AuthorId = 87 },
            new BookAuthor { BookId = 98, AuthorId = 88 },
            new BookAuthor { BookId = 99, AuthorId = 87 },
            new BookAuthor { BookId = 100, AuthorId = 87 },
            new BookAuthor { BookId = 101, AuthorId = 87 },
            new BookAuthor { BookId = 102, AuthorId = 89 },
            new BookAuthor { BookId = 103, AuthorId = 90 },
            new BookAuthor { BookId = 104, AuthorId = 91 },
            new BookAuthor { BookId = 105, AuthorId = 92 },
            new BookAuthor { BookId = 106, AuthorId = 93 },
            new BookAuthor { BookId = 107, AuthorId = 94 },
            new BookAuthor { BookId = 108, AuthorId = 95 },
            new BookAuthor { BookId = 109, AuthorId = 93 },
            new BookAuthor { BookId = 110, AuthorId = 96 },
            new BookAuthor { BookId = 111, AuthorId = 97 },
            new BookAuthor { BookId = 112, AuthorId = 98 },
            new BookAuthor { BookId = 113, AuthorId = 99 },
            new BookAuthor { BookId = 114, AuthorId = 100 },
            new BookAuthor { BookId = 115, AuthorId = 96 },
            new BookAuthor { BookId = 116, AuthorId = 101 },
            new BookAuthor { BookId = 117, AuthorId = 102 },
            new BookAuthor { BookId = 118, AuthorId = 103 },
            new BookAuthor { BookId = 119, AuthorId = 104 },
            new BookAuthor { BookId = 120, AuthorId = 105 },
            new BookAuthor { BookId = 121, AuthorId = 106 },
            new BookAuthor { BookId = 122, AuthorId = 107 },
            new BookAuthor { BookId = 123, AuthorId = 108 },
            new BookAuthor { BookId = 124, AuthorId = 109 },
            new BookAuthor { BookId = 125, AuthorId = 110 },
            new BookAuthor { BookId = 126, AuthorId = 111 },
            new BookAuthor { BookId = 127, AuthorId = 112 },
            new BookAuthor { BookId = 128, AuthorId = 113 },
            new BookAuthor { BookId = 129, AuthorId = 114 },
            new BookAuthor { BookId = 130, AuthorId = 115 },
            new BookAuthor { BookId = 131, AuthorId = 116 },
            new BookAuthor { BookId = 132, AuthorId = 117 },
            new BookAuthor { BookId = 133, AuthorId = 118 },
            new BookAuthor { BookId = 134, AuthorId = 119 },
            new BookAuthor { BookId = 135, AuthorId = 120 },
            new BookAuthor { BookId = 136, AuthorId = 121 },
            new BookAuthor { BookId = 137, AuthorId = 122 },
            new BookAuthor { BookId = 138, AuthorId = 123 },
            new BookAuthor { BookId = 139, AuthorId = 124 },
            new BookAuthor { BookId = 140, AuthorId = 125 },
            new BookAuthor { BookId = 141, AuthorId = 123 },
            new BookAuthor { BookId = 142, AuthorId = 126 },
            new BookAuthor { BookId = 143, AuthorId = 127 },
            new BookAuthor { BookId = 144, AuthorId = 128 },
            new BookAuthor { BookId = 145, AuthorId = 129 },
            new BookAuthor { BookId = 146, AuthorId = 130 },
            new BookAuthor { BookId = 147, AuthorId = 131 },
            new BookAuthor { BookId = 148, AuthorId = 132 },
            new BookAuthor { BookId = 149, AuthorId = 133 },
            new BookAuthor { BookId = 150, AuthorId = 147 },
            new BookAuthor { BookId = 151, AuthorId = 134 },
            new BookAuthor { BookId = 152, AuthorId = 135 },
            new BookAuthor { BookId = 153, AuthorId = 136 },
            new BookAuthor { BookId = 154, AuthorId = 137 },
            new BookAuthor { BookId = 155, AuthorId = 138 },
            new BookAuthor { BookId = 156, AuthorId = 139 },
            new BookAuthor { BookId = 157, AuthorId = 140 },
            new BookAuthor { BookId = 158, AuthorId = 141 },
            new BookAuthor { BookId = 159, AuthorId = 142 },
            new BookAuthor { BookId = 160, AuthorId = 143 },
            new BookAuthor { BookId = 161, AuthorId = 144 },
            new BookAuthor { BookId = 162, AuthorId = 145 },
            new BookAuthor { BookId = 163, AuthorId = 146 },
            new BookAuthor { BookId = 164, AuthorId = 146 }
        );
    }
}